# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder', '0002_auto_20170505_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(blank=True, max_length=120, null=True),
        ),
    ]
