# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-05 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reminder', '0004_auto_20170505_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='mobile',
            new_name='phone',
        ),
    ]
